// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("azurelogsingestion")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/azurelogsingestionexporter"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
