// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/featuregate"
)

var ProcessorResourcedetectionPropagateerrorsFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"processor.resourcedetection.propagateerrors",
	featuregate.StageBeta,
	featuregate.WithRegisterDescription("When enabled, allows errors returned from resource detectors to propagate in the Start() method and stop the collector."),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/37961"),
	featuregate.WithRegisterFromVersion("v0.121.0"),
)
